
const services = [`Service / General Information`,
`Maintenance Minder`,
`DTC Index and Troubleshooting`,
`DTC Advanced Diagnostics`,
`Engine Mechanical System`,
`Engine Cooling System`,
`Engine Lubrication System`,
`Engine Exhaust System`,
`Turbocharger Control System`,
`Fuel and Emissions Systems`,
`Fuel Supply System`,
`PGM-FI System`,
`Catalytic Converter System`,
`PCV System`,
`Electronic Throttle Control System`,
`Intake Air System and Exhaust System`,
`Starter Overhaul`,
`EVAP System`,
`Ignition System`,
`Cruise Control System`,
`Charging System`,
`Volt Battery Removal and Installation`,
`Clutch`,
`Manual Transmission`,
`CVT System`,
`TCM`,
`Brake System`,
`Electric Parking Brake System`,
`VSA System`,
`Driveline/Axle`,
`Front and Rear Suspension`,
`Adaptive Damper System`,
`Wheel and Tire System`,
`TPMS System`,
`Power Steering`,
`Steering Wheel and Column`,
`Climate Control System`,
`HVAC`,
`Audio and Visual System`,
`Navigation System`,
`CAN Communications`,
`Driving Support System`,
`Lane Keeping Assist System LKAS`,
`Keyless Access System`,
`Immobilizer System`,
`Interior Trim`,
`Dashboard Center Console`,
`Power Mirrors`,
`Gauges System`,
`Horn System`,
`Power Window`,
`Seat System`,
`Seat Belts System`,
`SRS Airbag System`,
`Moonroof System`,
`Lighting System`,
`Exterior Trim`,
`Windows Glass and Mirrors`,
`Bumpers`,
`Doors`,
`Tailgate System`,
`Trunk/Lid/Hood`,
`Wipers/Washers`,
`Body and Paint`,
`Body Repair`,
`Body Control Module`,
`Socket/Fuse/Relay/Switch`,
`Wire Harness and Ground Locations`,
`Electrical Wiring Diagrams`]

let servicesPDF = services.map((serv,index)=>{
       return  `mv SM_${index+1}.pdf SM_${index+1}${serv.replaceAll(" ", "_").replaceAll("/","-")}.pdf`
    })


console.log(servicesPDF)


